Repository gdelataillade/alarm, pull requests merged in 2023-03, with the labels that each got.

#11 Feature -> Multiple alarms management
  CHANGELOG.md
  README.md
  example/assets/mozart.mp3
  example/assets/nokia.mp3
  example/assets/one_piece.mp3
  example/assets/sample.mp3
  example/assets/star_wars.mp3
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner/mozart.mp3
  example/ios/Runner/nokia.mp3
  example/ios/Runner/one_piece.mp3
  example/ios/Runner/sample.mp3
  example/ios/Runner/star_wars.mp3
  example/lib/main.dart
  example/lib/screens/edit_alarm.dart
  example/lib/screens/home.dart
  example/lib/screens/ring.dart
  example/lib/widgets/tile.dart
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/SwiftAlarmPlugin.swift
  lib/alarm.dart
  lib/model/alarm_settings.dart
  lib/service/notification.dart
  lib/service/storage.dart
  lib/src/android_alarm.dart
  lib/src/ios_alarm.dart
  pubspec.yaml
Labels: work in progress

#20 Feature -> Add vibrations
  CHANGELOG.md
  README.md
  example/ios/Podfile.lock
  example/lib/screens/edit_alarm.dart
  example/lib/screens/ring.dart
  example/pubspec.lock
  ios/Classes/SwiftAlarmPlugin.swift
  lib/alarm.dart
  lib/model/alarm_settings.dart
  lib/src/android_alarm.dart
  lib/src/ios_alarm.dart
  pubspec.yaml
Labels: enhancement, work in progress

#25 Fix -> iOS crash when invalid audio url
  ios/Classes/SwiftAlarmPlugin.swift
Labels: reviewing
